/*
 * Claims Management API
 * API for managing insurance claims
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pe.claimsservice.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.client.JSON;

import java.io.IOException;
import java.time.LocalDate;
import java.util.*;

/**
 * ClaimMonthlyReport
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-24T23:30:41.403953400-05:00[America/Lima]", comments = "Generator version: 7.7.0")
public class ClaimMonthlyReport {
  public static final String SERIALIZED_NAME_TOTAL_CLAIMS = "totalClaims";
  @SerializedName(SERIALIZED_NAME_TOTAL_CLAIMS)
  private Integer totalClaims;

  public static final String SERIALIZED_NAME_CLAIMS_BY_STATUS = "claimsByStatus";
  @SerializedName(SERIALIZED_NAME_CLAIMS_BY_STATUS)
  private Map<String, Integer> claimsByStatus = new HashMap<>();

  public static final String SERIALIZED_NAME_MONTH = "month";
  @SerializedName(SERIALIZED_NAME_MONTH)
  private LocalDate month;

  public ClaimMonthlyReport() {
  }

  public ClaimMonthlyReport totalClaims(Integer totalClaims) {
    this.totalClaims = totalClaims;
    return this;
  }

  /**
   * Total number of claims for the month
   * @return totalClaims
   */
  @javax.annotation.Nullable
  public Integer getTotalClaims() {
    return totalClaims;
  }

  public void setTotalClaims(Integer totalClaims) {
    this.totalClaims = totalClaims;
  }


  public ClaimMonthlyReport claimsByStatus(Map<String, Integer> claimsByStatus) {
    this.claimsByStatus = claimsByStatus;
    return this;
  }

  public ClaimMonthlyReport putClaimsByStatusItem(String key, Integer claimsByStatusItem) {
    if (this.claimsByStatus == null) {
      this.claimsByStatus = new HashMap<>();
    }
    this.claimsByStatus.put(key, claimsByStatusItem);
    return this;
  }

  /**
   * Get claimsByStatus
   * @return claimsByStatus
   */
  @javax.annotation.Nullable
  public Map<String, Integer> getClaimsByStatus() {
    return claimsByStatus;
  }

  public void setClaimsByStatus(Map<String, Integer> claimsByStatus) {
    this.claimsByStatus = claimsByStatus;
  }


  public ClaimMonthlyReport month(LocalDate month) {
    this.month = month;
    return this;
  }

  /**
   * The month for which the report is generated
   * @return month
   */
  @javax.annotation.Nullable
  public LocalDate getMonth() {
    return month;
  }

  public void setMonth(LocalDate month) {
    this.month = month;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClaimMonthlyReport claimMonthlyReport = (ClaimMonthlyReport) o;
    return Objects.equals(this.totalClaims, claimMonthlyReport.totalClaims) &&
        Objects.equals(this.claimsByStatus, claimMonthlyReport.claimsByStatus) &&
        Objects.equals(this.month, claimMonthlyReport.month);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalClaims, claimsByStatus, month);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClaimMonthlyReport {\n");
    sb.append("    totalClaims: ").append(toIndentedString(totalClaims)).append("\n");
    sb.append("    claimsByStatus: ").append(toIndentedString(claimsByStatus)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("totalClaims");
    openapiFields.add("claimsByStatus");
    openapiFields.add("month");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ClaimMonthlyReport
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ClaimMonthlyReport.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ClaimMonthlyReport is not found in the empty JSON string", ClaimMonthlyReport.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ClaimMonthlyReport.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ClaimMonthlyReport` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ClaimMonthlyReport.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ClaimMonthlyReport' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ClaimMonthlyReport> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ClaimMonthlyReport.class));

       return (TypeAdapter<T>) new TypeAdapter<ClaimMonthlyReport>() {
           @Override
           public void write(JsonWriter out, ClaimMonthlyReport value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ClaimMonthlyReport read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ClaimMonthlyReport given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ClaimMonthlyReport
   * @throws IOException if the JSON string is invalid with respect to ClaimMonthlyReport
   */
  public static ClaimMonthlyReport fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ClaimMonthlyReport.class);
  }

  /**
   * Convert an instance of ClaimMonthlyReport to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

