/*
 * Claims Management API
 * API for managing insurance claims
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pe.claimsservice.model;

import com.google.gson.*;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.client.JSON;
import org.openapitools.client.model.ModelEnum;

import java.io.IOException;
import java.net.URI;
import java.time.LocalDate;
import java.util.*;

/**
 * Claim
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-24T23:30:41.403953400-05:00[America/Lima]", comments = "Generator version: 7.7.0")
public class Claim {
  public static final String SERIALIZED_NAME_CLAIM_ID = "claimId";
  @SerializedName(SERIALIZED_NAME_CLAIM_ID)
  private String claimId;

  public static final String SERIALIZED_NAME_CUSTOMER_ID = "customerId";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ID)
  private String customerId;

  public static final String SERIALIZED_NAME_SINISTER_TYPE = "sinisterType";
  @SerializedName(SERIALIZED_NAME_SINISTER_TYPE)
  private String sinisterType;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DATE_OF_INCIDENT = "dateOfIncident";
  @SerializedName(SERIALIZED_NAME_DATE_OF_INCIDENT)
  private LocalDate dateOfIncident;

  public static final String SERIALIZED_NAME_DOCUMENTATION = "documentation";
  @SerializedName(SERIALIZED_NAME_DOCUMENTATION)
  private List<URI> documentation = new ArrayList<>();

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING_DOCUMENTATION("PENDING_DOCUMENTATION"),
    
    PENDING("PENDING"),
    
    CLOSED("CLOSED");

    private ModelEnum value;

    StatusEnum(ModelEnum value) {
      this.value = value;
    }

    public ModelEnum getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(ModelEnum value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        ModelEnum value =  jsonReader.nextModelEnum();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      ModelEnum value = jsonElement.getAsModelEnum();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status = null;

  public Claim() {
  }

  public Claim claimId(String claimId) {
    this.claimId = claimId;
    return this;
  }

  /**
   * Unique identifier for the claim
   * @return claimId
   */
  @javax.annotation.Nullable
  public String getClaimId() {
    return claimId;
  }

  public void setClaimId(String claimId) {
    this.claimId = claimId;
  }


  public Claim customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * Unique identifier for the customer
   * @return customerId
   */
  @javax.annotation.Nullable
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }


  public Claim sinisterType(String sinisterType) {
    this.sinisterType = sinisterType;
    return this;
  }

  /**
   * Type of the sinister (e.g., accident, theft)
   * @return sinisterType
   */
  @javax.annotation.Nullable
  public String getSinisterType() {
    return sinisterType;
  }

  public void setSinisterType(String sinisterType) {
    this.sinisterType = sinisterType;
  }


  public Claim description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Description of the claim
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public Claim dateOfIncident(LocalDate dateOfIncident) {
    this.dateOfIncident = dateOfIncident;
    return this;
  }

  /**
   * Date of the incident
   * @return dateOfIncident
   */
  @javax.annotation.Nullable
  public LocalDate getDateOfIncident() {
    return dateOfIncident;
  }

  public void setDateOfIncident(LocalDate dateOfIncident) {
    this.dateOfIncident = dateOfIncident;
  }


  public Claim documentation(List<URI> documentation) {
    this.documentation = documentation;
    return this;
  }

  public Claim addDocumentationItem(URI documentationItem) {
    if (this.documentation == null) {
      this.documentation = new ArrayList<>();
    }
    this.documentation.add(documentationItem);
    return this;
  }

  /**
   * List of documentation URLs related to the claim
   * @return documentation
   */
  @javax.annotation.Nullable
  public List<URI> getDocumentation() {
    return documentation;
  }

  public void setDocumentation(List<URI> documentation) {
    this.documentation = documentation;
  }


  public Claim status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Claim claim = (Claim) o;
    return Objects.equals(this.claimId, claim.claimId) &&
        Objects.equals(this.customerId, claim.customerId) &&
        Objects.equals(this.sinisterType, claim.sinisterType) &&
        Objects.equals(this.description, claim.description) &&
        Objects.equals(this.dateOfIncident, claim.dateOfIncident) &&
        Objects.equals(this.documentation, claim.documentation) &&
        Objects.equals(this.status, claim.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claimId, customerId, sinisterType, description, dateOfIncident, documentation, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Claim {\n");
    sb.append("    claimId: ").append(toIndentedString(claimId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    sinisterType: ").append(toIndentedString(sinisterType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    dateOfIncident: ").append(toIndentedString(dateOfIncident)).append("\n");
    sb.append("    documentation: ").append(toIndentedString(documentation)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("claimId");
    openapiFields.add("customerId");
    openapiFields.add("sinisterType");
    openapiFields.add("description");
    openapiFields.add("dateOfIncident");
    openapiFields.add("documentation");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Claim
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Claim.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Claim is not found in the empty JSON string", Claim.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Claim.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Claim` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("claimId") != null && !jsonObj.get("claimId").isJsonNull()) && !jsonObj.get("claimId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `claimId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimId").toString()));
      }
      if ((jsonObj.get("customerId") != null && !jsonObj.get("customerId").isJsonNull()) && !jsonObj.get("customerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerId").toString()));
      }
      if ((jsonObj.get("sinisterType") != null && !jsonObj.get("sinisterType").isJsonNull()) && !jsonObj.get("sinisterType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sinisterType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sinisterType").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("documentation") != null && !jsonObj.get("documentation").isJsonNull() && !jsonObj.get("documentation").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentation` to be an array in the JSON string but got `%s`", jsonObj.get("documentation").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Claim.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Claim' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Claim> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Claim.class));

       return (TypeAdapter<T>) new TypeAdapter<Claim>() {
           @Override
           public void write(JsonWriter out, Claim value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Claim read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Claim given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Claim
   * @throws IOException if the JSON string is invalid with respect to Claim
   */
  public static Claim fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Claim.class);
  }

  /**
   * Convert an instance of Claim to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

